### ISSUE TITLE
drupal-core-strict for dev dependencies

### ISSUE THREAD

**Issue by jibran** [webflo/drupal-core-strict#3]
Right now it works well for required core dependencies but `composer update` still mess up the dev dependency.
I think a new package to pin the dev dependencies would be nice something like `composer require --dev drupal-dev-strict`.

**Comment by webflo** [comment]
Sounds good. Lets discuss the naming of the new packages, because i would move drupal-core-strict do drupal-composer and deprecate ``webflo/drupal-core-strict``

``drupal-composer/drupal-core-strict``
``drupal-composer/drupal-core-strict-dev`` or ``drupal-composer/drupal-core-dev-strict``

Or has anybody a better name?

**Comment by balsama** [comment]
I don't feel too strongly, but if you're moving it to the "drupal-composer" namespace, perhaps you could drop the "drupal" part of the package name. That would allow you to be more descriptive in the package name without it getting _too_ long. Maybe something like:

```
drupal-composer/strict-core-dependencies
drupal-composer/strict-core-dev-dependencies
```

**Comment by alexpott** [comment]
+1 I've tried to work around this for thunder but I think this is the way to go.

**Comment by jibran** [comment]
As a temp fix, I run this test.
```php
  /**
   * Tests require-dev package version is same as Drupal require-dev.
   */
  public function testRequireDev() {
    $project_json = json_decode(file_get_contents($this->root . '/composer.json'), TRUE);
    $core_json = json_decode(file_get_contents($this->root . '/webroot/core/composer.json'), TRUE);
    foreach ($core_json['require-dev'] as $package => $version) {
      $this->assertTrue(isset($project_json['require-dev'][$package]), sprintf('%s package is missing', $package));
      $this->assertSame($version, $project_json['require-dev'][$package], sprintf('%s version required for %s package.', $version, $package));
    }
  }
```

**Comment by alexpott** [comment]
Just did some work on this - see https://github.com/alexpott/strict-core-dev-dependencies. Feel free to fork in to drupal-composer and fix up the circle-ci integration.

**Comment by webflo** [comment]
I build a new command line tool to generate these packages.

- https://github.com/webflo/package-generator is the generic tool.
- https://github.com/webflo/package-generator-drupal is for drupal core. configuration is done in https://github.com/webflo/package-generator-drupal/blob/master/packages.yml (builders are custom and in src/)

Results

- https://github.com/webflo/drupal-core-strict 
- https://github.com/webflo/drupal-core-require-dev

**Comment by webflo** [comment]
@balsama i think you could fork package-generator-drupal and use it for lightning.

**Comment by balsama** [comment]
@webflo Thanks! This is awesome.
