### ISSUE TITLE
Using drupal-core-strict for PHP >=5.5.9 compatibility

### ISSUE THREAD

**Issue by aleksip** [webflo/drupal-core-strict#4]
I've been using drupal-core-strict to be able to install and update Drupal using Composer on a server with PHP 5.6. Until now it has worked fine, but now (with Drupal 8.4.4) I get the following:

```
  Problem 1
    - Installation request for symfony/cache v4.0.4 -> satisfiable by symfony/cache[v4.0.4].
    - symfony/cache v4.0.4 requires php ^7.1.3 -> your PHP version (5.6.33) does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/var-dumper v4.0.4 -> satisfiable by symfony/var-dumper[v4.0.4].
    - symfony/var-dumper v4.0.4 requires php ^7.1.3 -> your PHP version (5.6.33) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (5.6.33) does not satisfy that requirement.
  Problem 4
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (5.6.33) does not satisfy that requirement.
    - phpspec/prophecy 1.7.4 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.1.0].
    - Installation request for phpspec/prophecy 1.7.4 -> satisfiable by phpspec/prophecy[1.7.4].
```

If using drupal-core-strict results in getting exactly the versions of Drupal core's dependencies as they are specified in Drupal core's `composer.lock` file, I'm not sure how this is possible? Is this an issue with drupal-core-strict or am I mistaken in my assumption that Drupal 8 is compatible with PHP >=5.5.9? What would be the best way to ensure PHP >=5.5.9 compatibility with Composer installs?

**Comment by webflo** [comment]
``symfony/cache`` is not a core dependency afaik. Could you run "composer why symfony/cache" to see which package requires it?

**Comment by aleksip** [comment]
Thanks for your quick response! Indeed, it looks like Drupal Console's requirements are causing this.

**Comment by webflo** [comment]
👍
